version: '3.8'
services:
  db:
    image: postgres:alpine
    container_name: local_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Jigar@2003
      - POSTGRES_DB=portal
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - .:/app
volumes:
  postgres_data_dev:
